version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - sqlite_data:/var/www/database
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/var/www/public/api-docs.json
    volumes:
      - ./:/var/www
    networks:
      - laravel

volumes:
  sqlite_data:

networks:
  laravel:
